# Generated by Django 2.2.3 on 2019-07-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
    ]
