# Generated by Django 2.2.3 on 2019-07-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon_api', '0002_auto_20190718_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='urlOriginal',
        ),
        migrations.AlterField(
            model_name='photo',
            name='original',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
